USE_CAMERA_STUB := true

# inherit from the proprietary version
-include vendor/zte/n919/BoardConfigVendor.mk

TARGET_NO_BOOTLOADER := true
TARGET_BOARD_PLATFORM := msm7627a
TARGET_BOARD_PLATFORM_GPU := qcom-adreno203
TARGET_BOOTLOADER_BOARD_NAME := MSM8625QKUD 
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_ARCH_VARIANT := armv7-a
TARGET_ARCH_VRAIANT_CPU := cortex-a5
TARGET_ARCH_VARIANT_FPU := neon 
ARCH_ARM_HAVE_NEON := true
ARCH_ARM_HAVE_TLS_REGISTER := true
ARCH_ARM_HAVE_ARMV7A := true
ARCH_ARM_HAVE_VFP := true 
TARGET_CPU_SMP := true
TARGET_GLOBAL_CFLAGS +=  -mfpu=neon -mfloat-abi=softfp
TARGET_GLOBAL_CPPFLAGS += -mfpu=neon -mfloat-abi=softfp
USE_OPENGL_RENDERER := true
BORAD_REC_LANG_CHINESE := true

BOARD_KERNEL_CMDLINE := ttyMSM0,115200,n8 androidboot.hardware=qcom
BOARD_KERNEL_BASE := 0x00200000
BOARD_KERNEL_PAGESIZE := 2048
BOARD_MKBOOTIMG_ARGS := --ramdisk_offset 0x01000000
TARGET_PREBUILT_KERNEL := device/zte/n919/kernel

TARGET_USERIMAGES_USE_EXT4 := true
TARGET_SEC_INTERNAL_STORAGE := true
BOARD_USES_MMCUTILS := true
BOARD_HAS_LARGE_FILESYSTEM := true 
# fix this up by examining /proc/mtd on a running device
BOARD_BOOTIMAGE_PARTITION_SIZE := 13901824
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 16777216
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 805306368
BOARD_USERDATAIMAGE_PARTITION_SIZE :=1073741824
BOARD_FLASH_BLOCK_SIZE := 25600

BOARD_HAS_NO_SELECT_BUTTON := true
# Use this flag if the board has a ext4 partition larger than 2gb
#BOARD_HAS_LARGE_FILESYSTEM := true
TARGET_RECOVERY_INITRC := device/zte/n919/init.rc
TARGET_RECOVERY_PIXEL_FORMAT := "RGBX_8888"

# default props
ADDITIONAL_DEFAULT_PROPERTIES += ro.secure=0
ADDITIONAL_DEFAULT_PROPERTIES += ro.allow.mock.location=0
ADDITIONAL_DEFAULT_PROPERTIES += ro.debuggable=1
ADDITIONAL_DEFAULT_PROPERTIES += persist.service.adb.enable=1
ADDITIONAL_DEFAULT_PROPERTIES += ro.config.sec_storage=1
ADDITIONAL_DEFAULT_PROPERTIES += persist.sys.usb.config=mass_storage,adb

# USB Mounting
BOARD_USE_USB_MASS_STORAGE_SWITCH := true
#TARGET_USE_CUSTOM_LUN_FILE_PATH := "/sys/devices/android_usb/android0/f_mass_storage/lun%d/file"
BOARD_UMS_LUNFILE := "/sys/devices/platform/msm_hsusb/gadget/lun%d/file"
TARGET_RECOVERY_INITRC := device/zte/n919/recovery.rc
BOARD_VOLD_MAX_PARTITIONS := 20

TARGET_CORTEX_CACHE_LINE_32 := true
TW_INTERNAL_STORAGE_PATH := "/sdcard1"
TW_INTERNAL_STORAGE_MOUNT_POINT := "sdcard1"
TW_EXTERNAL_STORAGE_PATH := "/sdcard"
TW_EXTERNAL_STORAGE_MOUNT_POINT := "sdcard"
BOARD_DATA_DEVICE := /dev/block/mmcblk0p13
BOARD_DATA_FILESYSTEM := ext4
BOARD_DATA_FILESYSTEM_OPTIONS := rw
BOARD_SYSTEM_DEVICE := /dev/block/mmcblk0p12
BOARD_SYSTEM_FILESYSTEM := ext4
BOARD_SYSTEM_FILESYSTEM_OPTIONS := rw
BOARD_CACHE_DEVICE := /dev/block/mmcblk0p15
BOARD_CACHE_FILESYSTEM := ext4
BOARD_CACHE_FILESYSTEM_OPTIONS := rw
RECOVERY_GRAPHICS_USE_LINELENGTH := true
#TW_FLASH_FROM_STORAGE := true
#TW_HAS_REBOOT_BOOTLOADER := true
